name: Build

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-n-publish:
    name: Build and publish Python 🐍 distributions 📦 to Nexus
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build a binary wheel and a source tarball
        run: python setup.py sdist bdist_wheel

      - name: Publish a Python distribution to Nexus
        uses: sonatype-nexus-community/nexus-repo-github-action@master
        with:
          serverUrl: https://nexus.p.ecnl.ru/
          username: dns_ops
          password: 1662212
          format: pypi
          repository: ecdn-pypi
          coordinates: groupId=ru.edgecenter artifactId=certbot-dns-ecenter version=0.1.7
          assets: extension=tar.gz
          filename: ./dist/certbot-dns-ecenter-0.1.7.tar.gz
